name: Mind your language
on:
  issues:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created
      - edited
  pull_request_review_comment:
    types:
      - created
      - edited
jobs:
  echo_issue_comment:
    runs-on: ubuntu-latest
    name: profanity check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Profanity check step
        id: set-output
        uses: niharrs/mind-your-language-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Slack Notification
        if: steps.set_output.outputs.RESULT == 'User said something bad'
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: blockchain
          SLACK_USERNAME: moralPolice
          SLACK_COLOR: red
          SLACK_MESSAGE: ':warning: Profanity found on repository'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#   slackNotification:
#     if: ${{ steps.set_output.outputs.RESULT == 'User said something bad' }}
#     name: Slack Notification
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Slack Notification
#       uses: rtCamp/action-slack-notify@master
#       env:
#         SLACK_CHANNEL: blockchain
#         SLACK_USERNAME: moralPolice
#         SLACK_COLOR: red
#         SLACK_MESSAGE: ':warning: Profanity found on repository'
#         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
